# K-Nearest Neighbors(K-NN) Classifier

#### Import the Libriras

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### Load the Dataset

In [23]:
data = pd.read_csv('User_Data.csv')
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [24]:
data.shape

(400, 5)

In [25]:
x= data.iloc[:,2:4].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [26]:
x.shape

(400, 2)

In [27]:
y= data.iloc[:,-1]
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

#### Splitting the dataset into training and test set

In [28]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(x,y,test_size=0.20)

In [29]:
Xtrain.shape

(320, 2)

In [30]:
Xtest.shape

(80, 2)

#### Feature Scaling

In [31]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [32]:
Xtrain = scaler.fit_transform(Xtrain)
Xtrain

array([[ 0.05269418,  0.31845985],
       [-0.82452692,  0.31845985],
       [-0.04477483,  0.31845985],
       [ 0.83244628, -1.40676341],
       [ 0.05269418, -0.30618995],
       [ 0.1501632 ,  0.11024325],
       [ 0.44257023,  0.02100757],
       [-0.43465088, -0.78211361],
       [ 1.90460542, -0.27644472],
       [ 0.24763221,  1.12158103],
       [-1.409341  ,  0.37795031],
       [-1.11693396, -0.78211361],
       [ 1.41726035,  0.61591214],
       [-0.43465088, -0.84160406],
       [-1.50681001, -0.42517086],
       [ 0.54003925,  1.77597606],
       [-0.23971285, -0.48466132],
       [-0.14224384,  1.44877855],
       [ 0.92991529, -1.04982067],
       [-0.53211989, -1.52574433],
       [-0.92199594, -0.30618995],
       [-1.79921705,  0.02100757],
       [-1.409341  , -0.18720903],
       [-0.04477483,  0.13998848],
       [ 2.09954344, -0.81185884],
       [ 0.34510122, -0.18720903],
       [ 0.83244628,  1.41903332],
       [ 0.92991529,  2.22215449],
       [ 1.12485332,

In [33]:
Xtest = scaler.fit_transform(Xtest)
Xtest

array([[ 1.91887702,  1.02173597],
       [-0.30590793,  0.46130486],
       [ 0.22804046, -0.01506159],
       [-1.19582191, -1.0798807 ],
       [-0.75086492, -0.26725559],
       [-1.28481331, -1.24801003],
       [-0.12792513,  0.60141263],
       [ 1.74089422,  0.65745575],
       [-1.28481331, -0.46340647],
       [-0.21691653,  2.03051197],
       [ 0.76198884, -1.44416092],
       [ 1.29593723,  0.29317552],
       [ 0.67299745,  0.46130486],
       [-0.92884772, -0.46340647],
       [ 0.67299745,  0.06900308],
       [-0.66187352,  1.30195152],
       [ 1.47392003,  1.49810241],
       [ 1.20694583, -0.93977292],
       [ 0.31703186, -0.18319092],
       [-1.6407789 , -0.63153581],
       [-0.48389073, -0.3232987 ],
       [ 0.13904906, -0.40736336],
       [-1.10683051,  0.01295997],
       [-0.30590793,  0.20911086],
       [ 0.05005766, -0.29527714],
       [ 0.85098024,  1.9464473 ],
       [-0.30590793, -1.38811781],
       [ 0.13904906, -0.18319092],
       [-0.21691653,

#### Claculate the value of K

In [34]:
k = round(np.sqrt(Xtrain.shape[0]))
k1 = k%2
if k1==0:
    k=k-1;
else:
    k=k;
k

17

#### Fitting the K-NN Classifier

In [35]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(Xtrain,Ytrain)

KNeighborsClassifier(n_neighbors=17)

#### Predict the result

In [38]:
Ypred= knn.predict(Xtest)
Ypred

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0], dtype=int64)

#### Confiusion Matrix

In [39]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Ytest,Ypred)

array([[47,  3],
       [ 4, 26]], dtype=int64)

#### Accuracy Score

In [40]:
from sklearn.metrics import accuracy_score
print("Decision Tree Accuracy Score for Test dataset: ",accuracy_score(Ytest,Ypred)*100,"%")

Decision Tree Accuracy Score for Test dataset:  91.25 %


In [41]:
print("Decision Tree Accuracy Score for Train dataset: ",knn.score(Xtrain,Ytrain)*100,"%")

Decision Tree Accuracy Score for Train dataset:  90.625 %


#### Random Accuracy Check

In [44]:
accuracy=[]
for i in range(1,26):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(Xtrain,Ytrain)
    accuracy.append(accuracy_score(Ytest,knn.predict(Xtest)))

In [45]:
accuracy

[0.8,
 0.825,
 0.925,
 0.9125,
 0.925,
 0.9125,
 0.925,
 0.9125,
 0.9125,
 0.9125,
 0.9125,
 0.9,
 0.9125,
 0.9125,
 0.9125,
 0.9125,
 0.9125,
 0.9125,
 0.9125,
 0.9125,
 0.9125,
 0.9,
 0.9,
 0.9,
 0.9]